apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ariel
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
labels:
  - pairs:
      app.kubernetes.io/name: ariel
      app.kubernetes.io/component: relay
    includeSelectors: true
