apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ariel
resources:
  - ../../base
  - configmap.yaml
  - ingress.yaml
  - pvc.yaml
patches:
  - path: deployment-patch.yaml
images:
  - name: ariel-relay
    newName: ghcr.io/wu8685/ariel
    newTag: latest
